### ISSUE TITLE
not enough stars

### ISSUE THREAD

**Issue by PassTheMayo** [aurieh/goodshit#1]
dis shit is gud, need more ⭐️

**Comment by aurieh** [comment]
why is this even a thing

**Comment by PassTheMayo** [comment]
i don't know, but it helped me get banned from multiple discord servers ;)

**Comment by PassTheMayo** [comment]
btw i just got you two more stars

**Comment by sudomoose** [comment]
needs a LOT MORE STARS!

**Comment by aurieh** [comment]
smh
